[[body]]
== CSRs

The CTR configuration is selected by the currently active CTR control register, which is mctrcontrol when V=0, and vsctrcontrol when V=1.  In this document, when referring to the currently active CTR control register, ctrcontrol is used.

=== Machine Control Transfer Record Control (mctrcontrol)

The mctrcontrol register enables and configures the CTR capability while V=0.  The reset value is 0.  The CSR number is 0x381.

[width="100%",options="header",]
|===
4+|63:48 |47 |46
4+|_WPRI_ |DIROJMPINH |INDOJMPINH
|===

[width="100%",options="header",]
|===
|45 |44 |43 |42 |41 |40
|RETINH |CORSWAPINH |DIRJUMPINH |INDJUMPINH |DIRCALLINH |INDCALLINH
|===

[width="100%",options="header",]
|===
|39 |38 |37 |36 |35 |34 |33 |32:20
|_WPRI_ |ETEN |TKBRINH |NTBREN |TRETINH |INTRINH |EXCINH |_WPRI_
|===

[width="100%",options="header",]
|===
2+|19:16 |15:13 |12 |11 |10 |9 |8
2+|DEPTH |_WPRI_ |LCOFIFRZ |BPFRZ |RASEMU |STE |MTE
|===

[width="100%",options="header",]
|===
|7 4+|6:3 |2 |1 |0
|CLR 4+|_WPRI_ |U |S |M
|===

[width="100%",cols="18%,72%,10%",options="header",]
|===
|Field |Description |Access 
|M,S,U |Enable transfer recording in the selected privileged mode(s).  VS and VU modes can be enabled from <<_virtual_supervisor_control_transfer_record_control_vsctrcontrol, vsctrcontrol>>. |WLRL 

|CLR |When written to 1, zeroes all implemented CTR entries, regardless of the current CTR depth. Reads will always return 0 for this bit. |WLRL 

|MTE |If ETEN=1, enables recording of traps to M-mode when M=0.  See <<_external_traps, External Traps>>. |WLRL 

|STE |If ETEN=1, enables recording of traps to S-mode when S=0.  See <<_external_traps, External Traps>>. |WARL 

|RASEMU |Enables <<_ras_emulation_mode, RAS Emulation Mode>>. |WARL 

|BPFRZ |Set FROZEN on a breakpoint exception. See <<_freeze, Freeze>>. |WLRL 

|LCOFIFRZ |Set FROZEN on local counter overflow interrupt (LCOFI). See <<_freeze, Freeze>>. |WARL 

|DEPTH[3:0] a|
WARL field that selects the depth of the CTR array. Encodings:

‘0000 - 16

‘0001 - 32

‘0011 - 64

‘0111 - 128

‘1111 - 256

The depth of the CTR array dictates the number of entries to which the
hardware will record transfers. For a depth of N, the hardware will
record transfers to entries 0..N-1. mireg, mireg2, and mireg3 are
read-only 0 when miselect is in N..255.

It is unspecified which, if any, pre-existing CTR records are preserved
on a depth change, and which pre-existing records may be over-written.
It is strongly recommended that software set CLR on any writes that
modify DEPTH, to ensure that no pre-existing record state remains in any
inaccessible upper entries (N..255).

Which DEPTH values are supported is implementation-specific. An
implementation may opt to hardcode some or all of the bits in this
field, based on the depth options supported. See
<<_discovery, Discovery>>. |WLRL 

|EXCINH |Inhibit recording of exceptions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|INTRINH |Inhibit recording of interrupts.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|TRETINH |Inhibit recording of trap return instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|NTBREN |Enable recording of not-taken branch instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|TKBRINH |Inhibit recording of taken branch instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|ETEN |Enable recording of external traps, or traps from an enabled mode to a disabled mode. If ETEN=MTE=1, external traps to M-mode will be recorded. If ETEN=STE=1, external traps to S-mode will be recorded.  See <<_external_traps, External Traps>>. |WARL 

|INDCALLINH |Inhibit recording of indirect call instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|DIRCALLINH |Inhibit recording of direct call instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|INDJUMPINH |Inhibit recording of indirect jump instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|DIRJUMPINH |Inhibit recording of direct jump instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|CORSWAPINH |Inhibit recording of co-routine swap instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|RETINH |Inhibit recording of function return instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|INDOJMPINH |Inhibit recording of indirect other jump instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 

|DIROJMPINH |Inhibit recording of direct other jump instructions.  See <<_transfer_type_filtering, Transfer Type Filtering>>. |WARL 
|===

M, CLR, and DEPTH are required fields. S is required if S-mode
is implemented, and U is required if U-mode is implemented.  All other fields are
optional. 

All fields, save for DEPTH, should be 0 upon reset.  DEPTH may optionally have some bits hardcoded to 1, see <<_discovery, Discovery>>.  All unimplemented fields are read-only 0.

Bits 63:60 are reserved for custom extensions.

In RV32, mctrcontrol[63:32] can be accessed via mctrcontrolh (CSR 0x382).

[WARNING]
====
_More discussion needed on DEPTH.  Do we need variable depth?  Should HW reset CTR when it changes?  Should depth move to a separate CSR?  etc._
====

=== Supervisor Control Transfer Record Control (sctrcontrol)

The sctrcontrol register provides access to a subset of mctrcontrol. It is accessible from S-mode and VS-mode, such that S-mode accesses are redirected to mctrcontrol and VS-mode accesses are redirected to vsctrcontrol.  The CSR number is 0x181.

Bits 0 and 8 in sctrcontrol are read-only 0. As a result, S-mode and
VS-mode do not have access to the M and MTE fields in mctrcontrol.

In RV32, sctrcontrol[63:32] can be accessed via sctrcontrolh (CSR 0x182).

If S-mode is not implemented, access to sctrcontrol(h) results in an
illegal instruction exception.

=== Virtual Supervisor Control Transfer Record Control (vsctrcontrol)

The vsctrcontrol register is active when V=1, such that the hardware applies the CTR configuration from vsctrcontrol rather than that from mctrcontrol. It provides access to a subset of mctrcontrol, and additionally includes fields for configuring CTR when V=1.  VS-mode accesses to sctrcontrol are redirected to vsctrcontrol.  The reset value is 0.  The CSR number is 0x281.

[width="100%",options="header",]
|===
4+|63:48 |47 |46
4+|_WPRI_ |DIROJMPINH |INDOJMPINH
|===

[width="100%",options="header",]
|===
|45 |44 |43 |42 |41 |40
|RETINH |CORSWAPINH |DIRJUMPINH |INDJUMPINH |DIRCALLINH |INDCALLINH
|===

[width="100%",options="header",]
|===
|39 |38 |37 |36 |35 |34 |33 |32:20
|_WPRI_ |ETEN |BRINH |_WPRI_ |TRETINH |INTRINH |EXCINH |_WPRI_
|===

[width="100%",options="header",]
|===
2+|19:16 |15:13 |12 |11 |10 |9 |8
2+|DEPTH |_WPRI_ |LCOFIFRZ |BPFRZ |RASEMU |VSTE |0
|===

[width="100%",options="header",]
|===
|7 4+|6:3 |2 |1 |0
|CLR 4+|_WPRI_ |VU |VS |0
|===

[width="100%",cols="18%,72%,10%",options="header",]
|===
|Field |Description |Access 
|VS, VU |Enable transfer recording in the selected privileged mode(s). |WLRL 

|VSTE |If ETEN=1, enables recording of traps to VS-mode when VS=0.  See <<_external_traps, External Traps>>. |WLRL 
3+|Other fields access the corresponding field in 
<<_machine_control_transfer_record_control_mctrcontrol, mctrcontrol>>.
|===

[NOTE]
====
_Bit positions for VSTE, VS, and VU in vsctrcontrol match those for STE, S, and U in sctrcontrol, respectively. This is to accommodate an (unenlightened) guest OS that is unaware it is running with V=1._
====

In RV32, vsctrcontrol[63:32] can be accessed via vsctrcontrolh (CSR 0x282).

If the H extension is not implemented, access to vsctrcontrol(h) results
in an illegal instruction exception.

[WARNING]
====
_Do we want a VM to be able to change DEPTH?  Maybe a hypervisor would want to limit options?_
====

=== Machine Control Transfer Record Status (mctrstatus)

The mctrstatus register provides access to CTR status information, and is updated by the hardware when CTR is active (in an enabled privilege mode and not frozen).  The reset value is 0.  The CSR number is 0x383.

[width="100%",options="header",cols="30%,10%,10%,20%,30%"]
|===
|31:16 |15 |14 | 13:8 | 7:0
|_WPRI_ |FROZEN |WRAP |_WPRI_ |WRPTR
|===

[width="100%",cols="15%,75%,10%",options="header",]
|===
|Field |Description |Access
|WRPTR |Indicates the physical CTR array entry to be written next.  Set to 0 on CSR writes that set ctrcontrol.CLR.  Incremented on new transfers recorded, and decremented on qualified returns when ctrcontrol.RASEMU=1.  Wraps on increment when the value is all 1s, and on decrement when the value is 0.

The number of WRPTR bits supported is implementation-dependent, but must sufficient to index the array at the maximum depth supported (e.g., 4 bits for a max depth of 16).|WARL 
|WRAP   |WRPTR has wrapped.  Set when WRPTR has value depth-1 (where depth is based on ctrcontrol.DEPTH), and a CTR update causes WRPTR to be incremented.  Cleared when WRPTR has value zero and a CTR update causes WRPTR to be decremented (which only happens on returns when RASEMU=1), and on CSR writes that set ctrcontrol.CLR. |WLRL 
|FROZEN |Inhibit transfer recording. See <<_freeze, Freeze>>.|WLRL 

|===

Bits 31:28 are reserved for custom extensions.

[NOTE]
====
_Logical entry 0, accessed via mireg* when miselect=0x200, is always the physical entry preceding the WRPTR entry (WRPTR-1 % depth)._
====
[NOTE]
====
_Because the mctrstatus register is updated by hardware, writes should be performed with caution.  If a multi-instruction read-modify-write to mctrstatus is performed while CTR is active, such that a qualified transfer, or trap that causes CTR freeze, completes between the read and the write, a hardware update could be lost._
====
[NOTE]
====
_Exposing the WRPTR provides a more efficient means for synthesizng CTR entries.  If a qualified control transfer is emulated, the emulator can simply increment the WRPTR, then write the synthesized record to entry 0.  If a qualified function return is emulated while RASEMU=1, the emulator can clear ctrsource.V for entry 0, then decrement the WRPTR._

_Exposing the WRPTR may also allow support for Linux perf's https://lwn.net/Articles/802821[[.underline]#stack stitching#] capability._
====

=== Supervisor Control Transfer Record Status (sctrstatus)

The sctrstatus register is an S-mode and VS-mode (writable) alias to mctrstatus.  The CSR number is 0x183.

== Entry Registers

Control transfer records are stored in a CTR array, such that each array entry stores metadata for a single transfer.  The CTR array entries are logically accessed via the indirect register access mechanism defined by the
https://docs.google.com/document/u/0/d/1ZxTSUWX_9_VafWeA0l1ci9RFjmivLuZn-US9IbFOEWY/edit[[.underline]#Smcsrind/Sscsrind#]
extension. The miselect index range 0x200..0x2FF is reserved for CTR
entries 0..255. When miselect holds an entry in this range, mireg
provides access to
<<_control_transfer_record_source_ctrsource, ctrsource>>,
mireg2 provides access to
<<_control_transfer_record_target_ctrtarget, ctrtarget>>,
and mireg3 provides access to
<<_control_transfer_record_metadata_ctrdata, ctrdata>>.
Attempts to access to mireg[456] while miselect is in 0x200..0x2FF raise an
illegal instruction exception.

[WARNING]
====
_Would it be better for accesses to mireg[456] to be read-only zero?_
====
The standard indirect register access rules specified by Smcsrind/Sscsrind apply for CTR.  S-mode is able to access CTR entries using the siselect/sireg* interface, with the same behavior described for M-mode above.  Similarly, VS-mode is able to access CTR entries using siselect (really vsiselect) and sireg* (really vsireg*).  See <<_state_enable_access_control, State Enable Access Control>> for cases where CTR access from S-mode and VS-mode may be restricted.  

For select values in 0x200..0x2FF, vsireg* registers access the same entry register state as mireg* and sireg*, regardless of the privilege mode at the time of access.  There is not a separate set of entry registers for V=1.

Undefined bits in CTR entry registers are WPRI. Status fields may be added by future
extensions, and software should ignore but preserve any fields that it
does not recognize.

=== Control Transfer Record Source (ctrsource)

The ctrsource register contains the source virtual address (PC) of the
recorded transfer. The valid (V) bit is set by the hardware when a
transfer is recorded in the selected CTR array entry, and implies that
data in ctrsource, ctrtarget, and ctrdata is valid for this entry. All
fields are required.

ctrsource is an MXLEN-bit WARL register that must be able to hold all valid virtual addresses. It need not be capable of holding all possible invalid addresses. Prior to writing ctrsource, implementations may convert an invalid address into some other invalid address that ctrsource is capable of holding.

When XLEN < MXLEN, software access via *ireg will access only the lower XLEN bits of ctrsource, and implict writes (by recorded transfers) will be zero-extended.

[width="100%",cols="18%,72%,10%",options="header",]
|===
|MXLEN-1:XLEN|XLEN-1:1 |0
|0 |PC[XLEN-1:1] |V
|===

=== Control Transfer Record Target (ctrtarget)

The ctrtarget register contains the target (destination) virtual address
of the recorded transfer. MISP is optional, it is set by the hardware
when the recorded transfer is an instruction whose target or
taken/not-taken direction was mispredicted by the branch predictor. MISP
is read-only 0 when not implemented.

ctrtarget is an MXLEN-bit WARL register that must be able to hold all valid virtual addresses. It need not be capable of holding all possible invalid addresses. Prior to writing ctrtarget, implementations may convert an invalid address into some other invalid address that ctrtarget is capable of holding.

When XLEN < MXLEN, software access via *ireg2 will access only the lower XLEN bits of ctrtarget, and implict writes (by recorded transfers) will be zero-extended.

[width="100%",cols="18%,72%,10%",options="header",]
|===
|MXLEN-1:XLEN|XLEN-1:1 |0
|0 |PC[XLEN-1:1] |MISP
|===

=== Control Transfer Record Metadata (ctrdata)

The ctrdata register contains metadata for the recorded transfer. This
register is required, though all fields within it are optional.
Unimplemented fields are read-only 0.  Reset value is 0.

ctrdata is an MXLEN-bit register.  When XLEN < MXLEN, software access via *ireg3 will access only the lower XLEN bits of ctrdata.  

[width="100%",options="header",]
|===
4+|MXLEN-1:32 3+|31:16|15 2+|14:4 2+|3:0
4+|_WPRI_ 3+|CC |CCV 2+|_WPRI_ 2+|TYPE
|===

[width="100%",cols="15%,75%,10%",options="header",]
|===
|Field |Description |Access 
|TYPE[3:0] a|
Identifies the type of the control flow change recorded in CTR entry
ctrselect. Implementations that do not support this field will report 0.

0000 - Reserved

0001 - Exception

0010 - Interrupt

0011 - Trap return

0100 - Reserved

0101 - Taken branch

0110 - External trap

0111 - Reserved

1000 - Indirect call

1001 - Direct call

1010 - Indirect jump

1011 - Direct jump

1100 - Co-routine swap

1101 - Return

1110 - Other indirect jump

1111 - Other direct jump

|WLRL 

|CCV |Cycle Count Valid. See <<_cycle_counting, Cycle Counting>>. |WARL 

|CC[15:0] |Cycle Count, composed of the Cycle Count Exponent (CCE, in
CC[15:12]) and Cycle Count Mantissa (CCM, in CC[11:0]). See
<<_cycle_counting, Cycle Counting>>. |WARL 
|===

Bits 14:12 are reserved for custom extensions.

[NOTE]
====
_Like the transfer type inhibit bits in ctrcontrol, the ctrdata.TYPE bits leverage the E-trace itype encodings, with the addition of External Trap._
====
[WARNING]
====
_Do we need an External Trap type here?  Or just use Exception/Interrupt?  The target PC will be 0, so should be obvious this is an external trap.  Or maybe keeping External Trap type allows us to repurpose the target PC field?_
====

== State Enable Access Control

When Smstateen is implemented, the mstateen0.CTR bit controls access to CTR register state from privilege modes less privileged than M-mode.  When mstateen0.CTR=0, attempts from privilege modes less privileged than M-mode to access sctrcontrol, vsctrcontrol, sctrstatus, sireg* when siselect is in 0x200..0x2FF, or vsireg* when vsiselect is in 0x200..0x2FF, raise an illegal instruction exception.  When mstateen0.CTR=1, accesses to CTR register state behave as described in <<_csrs, CSRs>> and <<_entry_registers, Entry Registers>> above.

When mstateen0.CTR=0, qualified control transfers executed in privilege modes less privileged than M-mode will continue to implicitly update <<_entry_registers, Entry Registers>> and <<_machine_control_transfer_record_status_mctrstatus, mctrstatus>>.

If the H extension is implemented and mstateen0.CTR=1, the hstateen0.CTR bit controls access to supervisor CTR state (sctrcontrol, sctrstatus, and sireg* when siselect is in 0x200..0x2FF) when V=1.  When mstateen0.CTR=1 and hstateen0.CTR=1, VS-mode accesses to supervisor CTR state behave as described in <<_entry_registers, Entry Registers>>.  When mstateen0.CTR=1 and hstateen0.CTR=0, VS-mode accesses to supervisor CTR state that would have completed successfully if hstateen0.CTR was set raise a virtual instruction exception, while others raise an illegal instruction exception.

When hstateen0.CTR=0, qualified control transfers executed while V=1 will continue to implicitly update <<_entry_registers, Entry Registers>> and <<_machine_control_transfer_record_status_mctrstatus, mctrstatus>>.

The CTR bit is bit 55 in mstateen0 and hstateen0.

Bit 60 in mstateen0, defined by Smcsrind, can also restricts access to sireg*/siselect and vsireg*/vsiselect from privilege modes less privileged than M-mode.

== Behavior

CTR records qualified control transfers.  Control transfers are qualified if they meet the following criteria:

* The current privilege mode is enabled
* The transfer type is not inhibited
* mctrstatus.FROZEN is not set

Such qualified transfers update the <<_entry_registers, Entry Registers>> at logical entry 0, such that older entries are pushed down the stack (the record previously in entry 0 is pushed to entry 1, the record previously in entry 1 is pushed to entry 2, etc). If the CTR array is full, the oldest recorded entry (at DEPTH-1) is overwritten.

Recorded transfers will set the ctrsource.V bit to 1, and will update all implemented record fields. ctrsource.PC and ctrtarget.PC are required, other record fields are
optional.

[NOTE]
====
_In order to collect accurate and representative performance profiles while using CTR, it is recommended that hardware recording of control transfers incurs no added performance overhead, e.g., in the form of retirement or instruction execution restrictions that are not present when CTR is not recording transfers._
====

=== Privilege Mode Transitions

Transfers that change the privilege mode are a special case. What is
recorded, if anything, depends on whether the source (or origin) mode
and target mode are enabled for recording, and the transfer type (trap
or trap return).

Traps and trap returns between enabled modes are recorded as normal.
Traps from a disabled mode to an enabled mode, and trap returns from
an enabled mode back to a disabled mode, are partially recorded. In
such cases, the PC from the disabled mode (source PC for traps, and
target PC for trap returns) is 0. Trap returns from a disabled mode to
an enabled mode are not recorded. Traps from an enabled mode to an
disabled mode, known as external traps, are not recorded by default,
but see <<_external_traps, External Traps>> for how they
can be recorded.

Debug Mode is always inhibited. Transfers into and out of Debug Mode are
never recorded.

=== Transfer Type Filtering

By default, all control transfers within enabled privileged modes are recorded. Bits 47:32 in ctrcontrol provide a means for software to alter this behavior, by opting out of select transfer types, or opting into non-default types.  When implemented, all transfer type filter bits have reset value 0.  An implementation may opt to support any combination of transfer type filter bits, or none.

The transfer type filter bits leverage the type definitions specified
in Table 4.4, and described in Section 4.1.1, of the
https://github.com/riscv-non-isa/riscv-trace-spec/releases/download/v2.0rc2/riscv-trace-spec.pdf[[.underline]#RISC-V
Efficient Trace Spec v2.0#]. An exception is the ETEN bit, discussed in
<<_external_traps, External Traps>> below.

[NOTE]
====
_For a given implementation, if support for any transfer type filter bit results in reduced software performance, perhaps due to additional retirement restrictions, it is strongly recommended that this reduced performance apply only when the bit is set.  Alternatively, support for the bit may be omitted.  Maintaining software performance for the default CTR configuration, when all transfer type bits are cleared, is paramount._
====

==== External Traps

By default external traps are not recorded, but an optional handshake
mechanism exists to allow partial recording. Software running in the
target mode of the trap can opt-in to allowing CTR to record traps into
that mode even when the mode is inhibited. The MTE, STE, and VSTE bits
allow M-mode, S-mode, and VS-mode, respectively, to opt-in. Tools can
request to record External Traps by setting the ETEN bit. When an
External Trap occurs, only if both ETEN=1 and xTE=1, such that x is the
target privilege mode of the trap, will CTR record the trap. In such
cases, the target PC is 0, and the transfer type (if implemented) is
External Trap (6).
[NOTE]
====
_The external trap handshake allows both system software and the tools
control over what is exposed. M-mode firmware may always set
mctrcontrol.MTE=1, but a user-mode profiler may not wish to see any
traps. The driver can set sctrcontrol.ETEN=0 to ensure that external
traps are not recorded. On the other hand, a VM may wish to record
external traps from VU to VS, but the hypervisor may not wish to expose
traps from VU to HS. The VM will set ETEN=VSTE=1, but the hypervisor can
clear sctrcontrol.STE._

_No such mechanism exists for recording external trap returns, because
the external trap record includes all relevant information, and gives
the trap handler (e.g., an emulator) the opportunity to modify the
record._
====
[WARNING]
====
_Should external traps also depend on EXCINH/INTRINH?_

_STE allows recording of traps from U-mode to S-mode as well as from VS/VU-mode to HS-mode.  Fine to have the same bit do both?  Assumption is that the hypervisor can flip STE before entering a guest if it wants different behavior for U-to-S vs VS/VU-to-HS.  If we need a separate HTE bit then we'll need a new h* CSR._
====


The table below provides details on recording of privilege mode
transfers. Standard dependencies on FROZEN and transfer type inhibits
also apply, but are not covered by the table.

[width="100%",cols="18%,17%,30%,35%",]
|===
.2+|*Transfer Type* .2+| *Source Mode* 2+|*Target Mode*
|*Enabled* |*Inhibited*
.2+|*Trap* |*Enabled* |Recorded. |Recorded if ETEN=xTE=1, where x is target
mode. Target PC is 0, type is External Trap.

|*Inhibited* |Recorded, Source PC is 0. |Not recorded.

.2+|*Trap Return* |*Enabled* |Recorded. |Recorded, Target PC is 0.

|*Inhibited* |Not recorded. |Not recorded.
|===

If ETEN is implemented, MTE must be implemented as well, as must STE if
S-mode is implemented, and VSTE if VS-mode is implemented.

=== Cycle Counting

The ctrdata register may optionally include a count of CPU cycles
elapsed since the prior CTR record. The cycle counter increments only
while executing in an enabled privilege mode, and when FROZEN=0.

The elapsed cycle count value is represented by the CC field, which has
a mantissa component (Cycle Count Mantissa, or CCM) and an exponent
component (Cycle Count Exponent, or CCE). When CCE=0, CCM holds the raw
number of elapsed cycles. When CCE>0, the cycle count can be calculated
using the following formula:

[subs="specialchars,quotes"]
----
(2^12^ + CCM) << CCE-1
----
[WARNING]
====
_The 2^12^ is just a way to represent the leading 1.  Let me know if there's a better way to describe this._
====

When CCE>1, the cycle count granularity is reduced from 1 to 2^CCE-1^.
The calculated value is the result of rounding the elapsed cycles down
to the nearest multiple of 2^CCE-1^.
[NOTE]
====
_This rounding results in an undercount of elapsed cycles, for most
cases, when CCE>1. On average, the undercount will be (2^CCE-1^-1)/2.
Software can reduce the average undercount to 0 by adding (2^CCE-1^-1)/2
to each computed cycle count value when CCE>1._
====

The cycle count value is only valid when the Cycle Count Valid (CCV) bit
is set. CCV will be cleared for the first transfer recorded after the
cycle counter stopped incrementing for any reason. This includes
execution in an inhibited privilege mode, FROZEN=1, or other
implementation-specific cases, such as entry to a clock-gated low-power
mode.

An implementation that supports cycle counting must support CCV and all
CCM bits, but may support 0..4 exponent bits in CCE. Unimplemented CCE
bits are read-only 0. For implementations that support transfer type
filtering, it is recommended to support at least 3 exponent bits. This
allows capturing the full latency of most functions, when recording only
calls and returns.

The CC value saturates when CCM and all implemented bits in CCE are 1.

=== RAS Emulation Mode

When ctrcontrol.RASEMU=1, transfer recording behavior is altered to
emulate the behavior of a return-address stack (RAS).

* Indirect and direct calls are recorded as normal
* Function returns pop the most recent call, by invalidating entry 0 (V=0)
and rotating the CTR array, such that (invalidated) entry 0 moves to
entry DEPTH-1, and entries 1..DEPTH-1 move to 0..DEPTH-2.
* Co-routine swaps affect both a return and a call. Entry 0 is
overwritten.
* Other transfer types are inhibited
* <<_transfer_type_filtering, Transfer Type Filtering>> bits are ignored

[NOTE]
====
_Profiling tools often collect call stacks along with each sample. Stack
walking, however, is a complex and often slow process that may require
recompilation (e.g., -fno-omit-frame-pointer) to work reliably. With RAS
emulation, tools can ask CTR hardware to save call stacks even for
unmodified code._

_CTRs will contain only partial stacks in cases where the call stack
depth was greater than DEPTH, CTR recording was enabled at a lower point in the call stack than main(), or where the CTR array was cleared since
main()._
====

[NOTE]
====
_As described in <<_cycle_counting, Cycle Counting>>,
when CCV=1, the CC field provides the elapsed cycles since the prior CTR
entry was recorded. This introduces implementation challenges when
RASEMU=1 because, for each recorded call, there may have been several
recorded calls (and returns which “popped” them) since the prior
remaining call entry was recorded. The implication is that returns that
pop a call entry not only do not reset the cycle counter, but instead
add the CC field from the popped entry to the counter. For simplicity,
an implementation may opt to record CCV=0 for all calls when RASEMU=1._
====

=== Freeze

When mctrstatus.FROZEN=1, transfer recording is inhibited.  This bit can be set by hardware, as described below, or by software.

When ctrcontrol.LCOFIFRZ=1 and a local counter overflow interrupt
(LCOFI) is taken, mctrstatus.FROZEN is set by the CPU. This inhibits
CTR recording until software clears FROZEN. The LCOFI trap itself is not
recorded.
[NOTE]
====
_Freeze on LCOFI ensures that the execution path leading to the sampled
instruction (xepc) is preserved, and that the local counter overflow
interrupt (LCOFI) and associated Interrupt Service Routine (ISR) do not
displace any recorded transfer history state. It is the responsibility
of the ISR to clear FROZEN before xRET, if continued control transfer
recording is desired._

_LCOFI interrupt refers only to architectural traps directly caused by a local counter overflow interrupt. If a local counter overflow interrupt is recognized without a trap, for instance by reading mip, FROZEN is not automatically set._
====
Similarly, on a breakpoint exception with ctrcontrol.BPFRZ=1, FROZEN is
set by the CPU. The breakpoint exception itself is not recorded.  

[NOTE]
====
_Breakpoint exception refers to synchronous exceptions with a cause value of Breakpoint (3), regardless of source (ebreak, c.ebreak, Sdtrig); it does not include entry into Debug Mode, even in cores where this is implemented as an exception._
====

== Discovery

Software can discover supported CTR array depth values using the
following method:

* Write ‘0000 to ctrcontrol.DEPTH, then read back the value. The value
read represents the minimum supported depth.
* Write ‘1111 to ctrcontrol.DEPTH, then read back the value. The value
read represents the maximum supported depth.

All depths between the minimum and maximum are supported.

Software can discover implemented optional ctrcontrol fields by writing all 1s to all defined fields, then reading the value back. Unimplemented fields are read-only
0.

Software can discover implemented optional CTR entry fields by writing
all 1s to all defined fields in the <<_entry_registers, Entry Registers>> at
entry 0, then reading them back. Unimplemented fields are read-only 0.

== Opens

* Context filtering?
* Clear entries on depth change? Move depth field?
