[[intro]]
== Introduction

A method to record control flow transfer history is valuable for performance profiling usages, as well as for debug. Control flow transfers refer to jump instructions (including function calls and returns), taken branch instructions, traps, and trap returns.  Profiling tools like Linux perf collect control transfer history when sampling software execution, enabling users, and tools like AutoFDO, to identify hot paths for optimization.

Control flow trace capabilities offer very deep transfer history, but the volume of data produced can result in significant performance overheads due to memory bandwidth consumption, buffer management, and decoder overhead. The Control Transfer Records (CTR) extension provides a method to record a limited history in register-accessible internal chip storage, with the intent of dramatically reducing the performance overhead and complexity of collecting transfer history.

CTR defines a circular (FIFO) control transfer history buffer.  Recorded transfers are inserted to the head of the buffer, while older recorded transfers may be overwritten once the buffer is full. The source PC, target PC, and some optional metadata is stored for each recorded transfer.

The CTR buffer is accessible through an indirect CSR interface, such that software can specify which logical entry in the buffer it wishes to read or write.  Logical entry 0 is always the youngest recorded transfer, entry 1 is the next youngest, etc.

The machine-level extension *Smctr* encompasses all added CSRs and all behavior modifications for a hart, over all privilege levels. The associated supervisor-level extension *Ssctr* is essentially the same as *Smctr* except for excluding the machine-level CSRs and behaviors that should not be directly visible to supervisor level.

Smctr is dependent on the Smcsrind extension. Ssctr is dependent on the Sscsrind extension.

[WARNING]
====
_Text in warning blocks (such as this one) are comments for the reader, included while the spec is in development.  They will be resolved and removed before the spec is frozen._
====